{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Concurrent Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[$__range])) / sum(rate(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_errors_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severity Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service_name=\"fastapi-service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"fastapi-service\"} |= \"error\" [$__interval])"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (http_target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(http_errors_total[$__range])) by (http_target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{service_name=\"fastapi-service\", level=\"ERROR\"} |= ``"
    }
   ]
  }
 ]
}