server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: s3
    s3:
      endpoint: ${S3_ENDPOINT}
      insecure: ${S3_INSECURE}
      bucket: ${S3_TEMPO_BUCKET_NAME}
      region: ${AWS_REGION}
      access_key: ${AWS_ACCESS_KEY_ID}
      secret_key: ${AWS_SECRET_ACCESS_KEY}
      forcepathstyle: ${S3_FORCE_PATH_STYLE}
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
